title: Pytorch Fanatics
description: A simple CV library for Classification Tasks
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/MiHarsh/Pytorch_Fanatics/archive/refs/heads/main.zip
  tar_url: https://github.com/MiHarsh/Pytorch_Fanatics/tarball/main
  clone_url: https://github.com/MiHarsh/Pytorch_Fanatics.git
  owner_url: https://github.com/MiHarsh
show_downloads: true

plugins:
  - jekyll-seo-tag
  
image: https://github.com/MiHarsh/MiHarsh.github.io/blob/main/image/me.jpeg
